blank_issues_enabled: true
contact_links:
  - name: Openit Support
    url: https://t.me/yusteven
    about: è·å¾—å…³äºèŠ‚ç‚¹ / è®¢é˜…ä½¿ç”¨æ–¹é¢çš„æ”¯æŒ Telegram 24häººå·¥å®¢æœğŸ’â€â™‚ï¸
  - name: ShareCentrePro Channel
    url: https://t.me/ShareCentrePro
    about: æƒ³è·å–æˆ‘ä»¬çš„æœ€æ–°æ¶ˆæ¯ï¼Ÿæ¬¢è¿åŠ å…¥ Telegram çš„ ShareCentrePro
  - name: ShareCentrePro Group
    url: https://t.me/woisx
    about: æƒ³ä¸å¿—åŒé“åˆçš„ä¼™ä¼´ä»¬äº¤æµä¸€ä¸‹( Í¡Â° ÍœÊ– Í¡Â°)æ¬¢è¿åŠ å…¥ Telegram çš„ ShareCentre Pro || Chat
