blank_issues_enabled: false
contact_links:
  - name: Openit Support
    url: https://t.me/yusteven
    about: è·å¾—å…³äºèŠ‚ç‚¹ / è®¢é˜…ä½¿ç”¨æ–¹é¢çš„æ”¯æŒ Telegram æœ‰24hçš„äººå·¥å®¢æœğŸ’â€â™‚ï¸
  - name: ShareCentrePro Channel
    url: https://t.me/ShareCentrePro
    about: æƒ³è·å–æˆ‘ä»¬çš„æœ€æ–°æ¶ˆæ¯ï¼Ÿæ¬¢è¿åŠ å…¥ Telegram çš„è¿™ä¸ªé¢‘é“ï¼
