sub:
  - https://clash.ok1991.ml
# - https://raw.githubusercontent.com/freefq/free/master/v2
# - https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
# - https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
  - https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg
  - https://raw.githubusercontent.com/daycat/freeray/main/optimized.yaml
  - https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity.yml
  - https://raw.githubusercontent.com/yu-steven/openit/main/utils/pool/pool.yaml
  - https://proxies.bihai.cf/clash/proxies
  - https://fq.lonxin.net/clash/proxies
  - https://proxy.yugogo.xyz/clash/proxies
  - https://proxypoolss.fly.dev/clash/proxies
  - https://sspool.herokuapp.com/clash/proxies
  - https://free886.herokuapp.com/clash/proxies
# - https://42.194.196.226/clash/proxies
# - http://wxshi.top:9090/clash/proxies
# - http://39.106.12.141:8081/clash/proxies
# - http://49.233.28.108:1314/clash/proxies
