sub: # 注有#的是失效的订阅链接
# proxypool节点池
 # http开头
  - http://wxshi.top:9090/clash/proxies
# - http://149.248.8.112/clash/proxies
# - http://www.fuckgfw.tk/clash/proxies
# - http://42.194.196.226/clash/proxies
  - http://213.188.195.234/clash/proxies
# - http://104.128.81.6:8080/clash/proxies
  - http://39.106.12.141:8081/clash/proxies
  - http://49.233.28.108:1314/clash/proxies
  - http://139.196.162.200:9090/clash/proxies
  - http://proxypool.918848.xyz/clash/proxies
# - http://clash.3wking.com:12580/clash/proxies
 # https开头
  - https://www.sdufe.tk/clash/proxies
  - https://fq.lonxin.net/clash/proxies
# - https://122.10.97.150/clash/proxies
# - https://free.kingfu.cf/clash/proxies
  - https://free.dswang.ga/clash/proxies
  - https://proxies.bihai.cf/clash/proxies
# - https://hk.xhrzg2017.xyz/clash/proxies
# - https://proxy.whuboy.com/clash/proxies
  - https://proxy.yugogo.xyz/clash/proxies
  - https://proxy.leefake.xyz/clash/proxies
# - https://jiedian.faka77.tk/clash/proxies
  - https://ss.dswang.ga:8443/clash/proxies
# - https://baby-besitgift.com/clash/proxies
  - https://klausvpn.posyao.com/clash/proxies
  - https://proxypoolss.fly.dev/clash/proxies
  - https://sspool.herokuapp.com/clash/proxies
  - https://proxypool.laowang.me/clash/proxies
  - https://free886.herokuapp.com/clash/proxies
# - https://proxypool.remon602.ga/clash/proxies
  - https://us-proxypool.herokuapp.com/clash/proxies
  - https://eu-proxypool.herokuapp.com/clash/proxies
# openit
  - https://raw.githubusercontent.com/yu-steven/openit/main/Clash.yaml #openit回环订阅
  - https://raw.githubusercontent.com/yu-steven/openit/main/utils/pool/pool.yaml #openit入库订阅
# TopPreeProxy
  - https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/sub/sub_merge_yaml.yml
# freev2
  - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fraw.githubusercontent.com%2Fyu-steven%2Fopenit%2Fmain%2Fsub%2Fhelol%2Ffeiniao
  - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fraw.githubusercontent.com%2Fyu-steven%2Fopenit%2Fmain%2Fsub%2Fhelol%2Fckcloud
  - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fraw.githubusercontent.com%2Fyu-steven%2Fopenit%2Fmain%2Fsub%2Fhelol%2Fcirclecloud123
