name: Base64
on: 
  push:
    paths:
      - 'url'
  workflow_dispatch:
jobs:
  my-job:
    name: Base64 Encode
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # personal access token
        token: ${{ secrets.BASE64_NAME }}
    - name: config git
      run: git config --global user.name "github-actions[bot]"&&git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Write
      run: base64 url > long
    - name: push code
      run: |
        pull code
        chmod +x ./update-repo.sh&&./update-repo.sh
