name: Nodes
on: 
  push:
    paths:
      - 'url'
  workflow_dispatch:
jobs:
  my-job:
    name: Encode & Translate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 启动subconverter
      run: ./utils/subconverter/subconverter &
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 配置git
      run: |                 
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
    - name: url > https
      run: |
         base64 url > https -w 0
    - name: 提交更改1
      run: ./.github/update-repo.sh || true
    - name: long & clash
      run: |
         wget "http://0.0.0.0:25500/sub?target=mixed&url=https://raw.githubusercontent.com/yu-steven/openit/main/https&emoji=true" -O long || true
         wget "http://0.0.0.0:25500/sub?target=clash&url=https://raw.githubusercontent.com/yu-steven/openit/main/https&config=https://raw.githubusercontent.com/yu-steven/openit/main/sub/rule.ini&emoji=true&fdn=true&sort=true&udp=true" -O Clash.yaml || true
         wget "http://0.0.0.0:25500/sub?target=quanx&url=https://gist.githubusercontent.com/yu-steven/7543393c0db8b1a3dd477cb4f5676c33/raw/55eb6909a083ccfece031341c3067914ea43760c/https
    - name: 提交更改2
      run: ./.github/update-repo.sh || true
  long:
    needs: my-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/long
  HTTPS:
    needs: my-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/https
  Clash:
    needs: my-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Clash.yaml
  Quanx:
   needs: my-job
   runs-on: ubuntu-latest
   steps:
   - name: CDN
     run: sleep 1 #curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Quanx.conf
