name: Nodes
on: 
  push:
    paths:
      - 'url'
  workflow_dispatch:
jobs:
  my-job:
    name: Encode & Translate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 配置git
      run: |                 
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
    - name: url > https
      run: base64 url > https -w 0
    - name: 提交更改1
      run: ./.github/update-repo.sh || true
    - name: long & clash
      run: ./utils/subconverter/subconverter -g && mv ./utils/subconverter/long ./long || true && mv ./utils/subconverter/Clash.yaml ./Clash.yaml || true
    - name: 提交更改2
      run: ./.github/update-repo.sh || true
  long:
    needs: my-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/long
  HTTPS:
    needs: my-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/https
  Clash:
    needs: my-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Clash.yaml
  Quanx:
   needs: my-job
   runs-on: ubuntu-latest
   steps:
   - name: CDN
     run: sleep 1 #curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Quanx.conf
