name: url1
on: 
  push:
    paths:
      - 'url'
  workflow_dispatch:

#TODO 将需要手动入库的节点放置在./url里，系统会自动处理并输出到./utils/pool/output.txt ./utils/pool/output.yaml以引入节点池
jobs:
  re-job:
    name: url1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: git config --local user.name "GitHub Actions"; git config --local user.email "actions@github.com"
    - name: sed url1
      run: | #sed -n '/:\/\//p' bot >> ./openit/url #提取bot文本中符合行中有://字符的行追加到url文本结尾
         sed -i '/^sub:/d' url           #删除以sub:开头的行
         sed -i '/^$/d' url              #删除空白行
         sed -i -r '/^\s*$/d' url        #删除带有空格或制表符的空行
         sed -i 's/^[[:space:]]*//g' url #删除行头空格和tab，对齐行头
    - name: subconverter
      run: | 
         base64 ./url > ./utils/subconverter/b64 -w 0
         ./utils/subconverter/subconverter -g --artifact "fix"; rm ./utils/subconverter/b64
         base64 -d ./utils/subconverter/fix > ./utils/rm/url; rm ./utils/subconverter/fix
    - name: remove & rename
      run: cd ./utils/rm/ && npm ci && npm start
    - name: ./url
      run: rm ./utils/rm/url; mv ./utils/rm/out ./url; sort url -o url #整理url文件
    - name: ./url -> ./utils/pool/into.yaml & .../output.txt & .../output.yaml
      run: | 
         mv ./utils/pool/output.yaml ./utils/subconverter/push1.yaml
         base64 ./url > ./utils/subconverter/push2 -w 0
         ./utils/subconverter/subconverter -g --artifact "into"
         ./utils/subconverter/subconverter -g --artifact "push"
         mv ./utils/subconverter/push.yaml ./utils/subconverter/output.yaml
         ./utils/subconverter/subconverter -g --artifact "output"
         sed -i '1,197d' ./utils/subconverter/into.yaml
         sed -i -e 's/!<str> //g' -e '1,197d' ./utils/subconverter/output.yaml
         rm ./utils/subconverter/push1.yaml ./utils/subconverter/push2
         mv ./utils/subconverter/into.yaml ./utils/subconverter/output.txt ./utils/subconverter/output.yaml -t ./utils/pool/
    - name: git push
      run: git status -s && git pull origin main && git add . && git commit -m "$(date '+%Y.%m.%d %H:%M:%S') 节点入库" && git push origin main
