name: url1
on: 
  push:
    paths:
      - 'url'
  workflow_dispatch:

#TODO 将需要手动入库的节点放置在./url里，系统会自动处理并输出到./utils/pool/pool.yaml以引入节点池
jobs:
  re-job:
    name: url1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: pool.yaml
      run: | #sed -n '/:\/\//p' bot >> ./openit/url #提取bot文本中符合行中有://字符的行追加到url文本结尾
         sed -i 's/^[ \t]*//g' url #删除行头空格和tab，对齐行头
         sed -i '/^sub:/d' url     #删除以sub:开头的行
         sed -i '/^$/d' url        #删除空白行
         sed -i -r '/^\s*$/d' url  #删除带有空格或制表符的空行
         sort url -o url           #整理url文件
         base64 ./url > ./utils/subconverter/pool -w 0
         ./utils/subconverter/subconverter -g --artifact "pool" && rm ./utils/subconverter/pool
         sed -i '1,198d' ./utils/subconverter/pool.yaml #删除pool.yaml开头1-198行
         mv ./utils/subconverter/pool.yaml ./utils/pool/pool.yaml
         
    - name: git push
      run: git pull origin main && git add . && git commit -m "$(date '+%Y.%m.%d %H:%M:%S') 节点入库" && git push origin main
